name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
    - run: git add dist -f
    - run: git commit -m 'Deploy'
    - run: git push origin `git subtree split --prefix dist main`:gh-pages --force
